version: "3.1"

services:
  postgres1:
    image: postgres:latest
    container_name: users-db
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
    ports:
      - "5432:5432"

  postgres2:
    image: postgres:latest
    container_name: posts-db
    environment:
      POSTGRES_DB: postsdb
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
    ports:
      - "5433:5432"
